baseURL = "https://circly-ai-test.pages.dev"
locale = "de"
title = "Circly-AI-Test"

[params]
  author = "Herwig"
  description = "Supply Chain Intelligence. Aus der Praxis, für die Praxis."

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false
